language: php
php: 7.1
sudo: required
dist: trusty
addons:
  chrome: stable
install:
  - mysql -uroot -e "create database dusk"
  - |
    echo -e "[mysqld]
    character_set_server=utf8mb4
    collation_server=utf8mb4_unicode_ci
    innodb_large_prefix=ON
    innodb_file_format=Barracuda
    innodb_file_format_max=Barracuda" | sudo tee /etc/mysql/conf.d/travis.cnf
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
before_script:
  - sudo /etc/init.d/mysql restart
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - php artisan key:generate
  - php artisan migrate --seed
script:
  - php artisan dusk
